name: Build Linux x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++ libcurl4-openssl-dev
      - name: Install Qt5.15
        run: sudo apt-get install -y qt5-default qtbase5-dev qttools5-dev qttools5-dev-tools
      - name: Build
        run: |
          mkdir build-linux-x64
          cd build-linux-x64
          cmake ..
          make
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: walltaker_universal-linux-x64
          path: build-linux-x64/**
