name: Build Windows x64

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: choco install cmake -y
      - name: Install Qt6
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.6.2'
          arch: win64_msvc2019_64
      - name: Build
        run: |
          mkdir build-win-x64
          cd build-win-x64
          cmake .. -G "Visual Studio 17 2022" -A x64
          cmake --build . --config Release
      - name: Package with windeployqt
        run: |
          cd build-win-x64/Release
          windeployqt walltaker_universal.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: walltaker_universal-windows-x64
          path: build-win-x64/Release/walltaker_universal.exe
